spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      platform: h2

  datasource:
    url: jdbc:h2:mem:development;MODE=MYSQL;DB_CLOSE_DELAY=-1
    # jdbc:h2:mem:... 에서 'mem'은 h2 메모리 모드를 의미한다. H2 데이터베이스는 메모리 기반 / 파일 기반 / TCP 서버 모드가 있는데, 메모리 기반으로 URL을 설정하게 되면 애플리케이션 종료 시 데이터베이스가 초기화된다.
    # 외부 서버의 데이터베이스에 작업할 때에는 이와 같이 url을 지정해 어떤 데이터베이스에 접근할 것인지 설정해주어야 함.
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console